routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
define('SEGMENT',request()->segment(1));

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('success','UserContoller@success_message');
Route::get('privacy-policy','App\Http\Controllers\HomeController@privacy_policy');
Route::get('terms-and-conditions','App\Http\Controllers\HomeController@terms_and_conditions');
Route::get('faqs','App\Http\Controllers\HomeController@faqs');
Route::get('about-us','App\Http\Controllers\HomeController@about_us');
Route::get('notification','App\Http\Controllers\Admin\UserFcmTokenController@sendNotification');
Route::get('show-order-invoice/{id}','App\Http\Controllers\Admin\OrderController@show_order_invoice');

Route::resource('narega','App\Http\Controllers\NaregaController');
Route::get('narega-worker-list','App\Http\Controllers\NaregaController@narega_worker_list');
Route::get('narega-export','App\Http\Controllers\NaregaController@narega_export');



Route::group(['prefix'=>'admin','namespace'=>'App\Http\Controllers\Admin'],function(){

	Route::get('/', 'UserContoller@login');
	Route::get('login', 'UserContoller@login');
	Route::post('login', [ 'as' => 'login', 'uses' => 'UserContoller@login']);
	Route::post('do-login','UserContoller@do_login');
	Route::get('logout','UserContoller@logout');
	Route::view('forgot_password', 'auth.reset_password')->name('password.reset');
	Route::post('reset-password','UserContoller@reset_password');
    Route::get('save-info','UserContoller@saveinfo');
    Route::get('save-info1','UserContoller@saveinfo1');

	Route::middleware(['admin'])->group(function () {

		Route::get('dashboard','DashboardController@index');
        Route::get('my-profile','DashboardController@myProfile')->name('my.profile');
        Route::get('edit-profile','DashboardController@editProfile')->name('edit.profile');
        Route::post('edit-profile','DashboardController@editProfilePost')->name('edit.profile.post');
		Route::get('change-password','DashboardController@changePassword')->name('change.password');
        Route::post('change-password','DashboardController@changePasswordPost')->name('change.password.post');
		Route::resource('user','UserContoller');
		Route::post('update-status','UserContoller@update_status');
		Route::get('ajax','UserContoller@ajax');
		Route::resource('cms','CmsController');
		Route::resource('content','ContentController');
		Route::resource('category','CategoryController');
		Route::resource('subcategory','SubCategoryController');
		Route::resource('product','ProductController');
		Route::resource('banner','BannerController');
		Route::resource('promocode','PromoCodeController');
		Route::post('banner-add/{id}','PlaylistController@banner_add_post');
		Route::get('profile','UserContoller@profile')->name('profile');
        Route::get('orders/{id?}','OrderController@orders')->name('orders.index');
        Route::resource('order','OrderController');
        Route::get('/update-order-status/{order_id}/{user_id}/{order_Status}','OrderController@update_order_status');
        Route::post('/update-order-status','OrderController@update_order_status1');
        Route::resource('deliverycharge','DeliveryChargeController');
		Route::resource('musiccategory','MusicCategoryController');
		Route::resource('audio','AudioController');
		Route::resource('video','VideoController');
		Route::resource('lyric','LyricController');
		Route::resource('subunit','SubunitController');
		Route::resource('color','ColorController');
		Route::resource('unit','UnitController');



	});


});

app/Models/Audio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Audio extends Model
{
    use HasFactory;
    public function getThumbnailAttribute($value) {
        return file_checker($value, 'avatar');
    }
    public function getImageAttribute($value) {
        return file_checker($value, 'avatar');
    }
    public function getFileAttribute($value) {
        return file_checker($value, 'audio');
    }
    public function AudioCategory() {
        return $this->hasMany(AudioCategory::class);
    }



}

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/UnitController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Models\Unit;
use Illuminate\Http\Request;
use Validator;
class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Unit::where(['is_deleted'=>0])->get();
        return view('admin.unit.index',compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.unit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $validator = Validator::make($request->all(),[
            'name' => 'required',
            ]);
            if($validator->fails())
            {
                return response()->json(['status' => 0, 'errors' => $validator->errors()]);
            }
            
            $unit = new Unit();
            $unit->name = $request->name;
            if($unit->save())
            {
                return response()->json(['status' => 1, 'msg' => 'Unit added successfully']);
            }
            else
            {
                return response()->json(['status' => -1, 'msg' => 'Unit not added']);
            }
        }
        catch (\Throwable $e) {
            return response()->json(['status' => -1, 'msg' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        return view('admin.unit.edit',compact('unit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unit $unit)
    {
        try {
            $validator = Validator::make($request->all(),[
            'name' => 'required',
            ]);
            if($validator->fails())
            {
                return response()->json(['status' => 0, 'errors' => $validator->errors()]);
            }
            
            $unit->name = $request->name;
            if($unit->save())
            {
                return response()->json(['status' => 1, 'msg' => 'Unit added successfully']);
            }
            else
            {
                return response()->json(['status' => -1, 'msg' => 'Unit not added']);
            }
        }
        catch (\Throwable $e) {
            return response()->json(['status' => -1, 'msg' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Unit $unit)
    {
        $unit->is_deleted = 1;
        if($unit->save()) {
            return redirect('admin/unit')->with('Unit deleted successfully.');
        }
        else {
            return back()->with('Unit not deleted.');
        }
    }
}

resources/views/admin/unit/create.blade.php
@extends('layouts.admin')
@section('title','Unit Create')
@section('content')
@push('stylesheets')
@endpush
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Unit</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url(SEGMENT.'/dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item" aria-current="page"><a href="{{url(SEGMENT.'/unit')}}">Unit</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Add</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                    
                   <div class="col-md-12">
                    <div class="alert d-none" role="alert" id="error-msg"></div>
                       
                    
                    <form class="form-horizontal add-form" enctype="multipart/form-data" data-url="{{route('color.index')}}" action="{{url(SEGMENT.'/color')}}" method="post" id="exampleValidation">
                    @csrf
                   <div class="card">
                    
                    
                            <div class="card-body">
                            <div class="form-group row">
                                    <label class="col-md-2 m-t-15"></label>
                                    <div class="col-md-10">
                                         <a href="{{url(SEGMENT.'/unit')}}" class="btn btn-info pull-right btn-sm" data-toggle="tooltip" title="All Unit" style="float:right;">
                                            <span class="btn-label">
                                                <i class="fa fa-list"></i>
                                            </span>
                                            All Unit
                                        </a>
                                    </div>
                            </div>
                                
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Name</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control name" id="name" name="name" placeholder="Enter name" value="">
                                        <div id="hsvflat"></div>
                                        <span class="text-danger">{{$errors->first('name')}}</span>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="border-top">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{url(SEGMENT.'/unit')}}" class="btn btn-danger resetBtn">Cancel</a>
                                    
                                </div>
                            </div>
                        </div>
                    </form>
                        </div>
                    
                   
                </div>
                <!-- ============================================================== -->
             
                
                <!-- ============================================================== -->
                <!-- Recent comment and chats -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
           
           @push('scripts')
            <script src="{{asset('dist/js/common/event.js')}}"></script>
    @endpush
@endsection

resources/views/admin/unit/edit.blade.php
@extends('layouts.admin')
@section('title','Unit Edit')
@section('content')
@push('stylesheets')
@endpush
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Unit</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url(SEGMENT.'/dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item" aria-current="page"><a href="{{url(SEGMENT.'/unit')}}">Unit</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                    
                   <div class="col-md-12">
                    <div class="alert d-none" role="alert" id="error-msg"></div>
                       
                    
                    <form class="form-horizontal add-form" enctype="multipart/form-data" data-url="{{route('unit.index')}}" action="{{url(SEGMENT.'/unit/'.$unit->id)}}" method="post" id="exampleValidation">
                    @csrf
                    @method("PUT")
                   <div class="card">
                    
                    
                            <div class="card-body">
                            <div class="form-group row">
                                    <label class="col-md-2 m-t-15"></label>
                                    <div class="col-md-10">
                                         <a href="{{url(SEGMENT.'/unit')}}" class="btn btn-info pull-right btn-sm" data-toggle="tooltip" title="All Unit" style="float:right;">
                                            <span class="btn-label">
                                                <i class="fa fa-list"></i>
                                            </span>
                                            All Unit
                                        </a>
                                    </div>
                            </div>
                                
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Name</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control name" id="name" name="name" placeholder="Enter name" value="{{$unit->name}}">
                                        <div id="hsvflat"></div>
                                        <span class="text-danger">{{$errors->first('name')}}</span>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="border-top">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{url(SEGMENT.'/unit')}}" class="btn btn-danger resetBtn">Cancel</a>
                                    
                                </div>
                            </div>
                        </div>
                    </form>
                        </div>
                    
                   
                </div>
                <!-- ============================================================== -->
             
                
                <!-- ============================================================== -->
                <!-- Recent comment and chats -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
           
           @push('scripts')
            <script src="{{asset('dist/js/common/event.js')}}"></script>
    @endpush
@endsection

resources/views/admin/unit/show.blade.php
@extends('layouts.admin')
@section('content')

            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Contents</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item" aria-current="page"><a href="{{url('content')}}">Contents</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">View</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                   <div class="col-md-12">
                   @if(session('message'))
                <p class="alert alert-success">{{session('message')}}</p>
            @endif
                   <div class="card">
                            <div class="card-body">
                               
                                 <div class="form-group row">
                                    <label class="col-md-2 m-t-15"><h5 class="card-title">All Contents</h5></label>
                                    <div class="col-md-10">
                                         <a href="{{url('content')}}" class="btn btn-info pull-right btn-sm" data-toggle="tooltip" title="All Content" style="float:right;">
                                            <span class="btn-label">
                                                <i class="fa fa-list"></i>
                                            </span>
                                            All Content
                                        </a>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                   <table class="table table-striped table-bordered">
                               <tbody>
                                   
                                    <tr>
                                        <th style="width:30%">Title</th>
                                        <td style="width:70%">{{$content->title}}</td>
                                    </tr>
                                    <tr>
                                        <th style="width:30%">Sub Title</th>
                                        <td style="width:70%">{{$content->sub_title}}</td>
                                    </tr>
                                    <tr>
                                        <th style="width:30%">Description</th>
                                        <td style="width:70%">{!! $content->description !!}</td>
                                    </tr>
                                                                        <tr>
                                        <th style="width:30%">Image</th>
                                        <td style="width:70%">
                                            <div class="avatar-xxl">
                                                <img src="{{url('images/'.$content->image)}}" class="avatar-img"> 
                                            </div>
                                        </td>
                                    </tr>
                                                                        <tr>
                                        <th>Status</th>
                                        <td>Active</td>
                                    </tr>
                                </tbody>
                            </table>
                                </div>

                            </div>
                        </div>
                        </div>
                    
                   
                </div>
                <!-- ============================================================== -->
             
                
                <!-- ============================================================== -->
                <!-- Recent comment and chats -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
          
@endsection