routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
define('SEGMENT',request()->segment(1));

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('success','UserContoller@success_message');
Route::get('privacy-policy','App\Http\Controllers\HomeController@privacy_policy');
Route::get('terms-and-conditions','App\Http\Controllers\HomeController@terms_and_conditions');
Route::get('faqs','App\Http\Controllers\HomeController@faqs');
Route::get('about-us','App\Http\Controllers\HomeController@about_us');
Route::get('notification','App\Http\Controllers\Admin\UserFcmTokenController@sendNotification');
Route::get('show-order-invoice/{id}','App\Http\Controllers\Admin\OrderController@show_order_invoice');

Route::resource('narega','App\Http\Controllers\NaregaController');
Route::get('narega-worker-list','App\Http\Controllers\NaregaController@narega_worker_list');
Route::get('narega-export','App\Http\Controllers\NaregaController@narega_export');



Route::group(['prefix'=>'admin','namespace'=>'App\Http\Controllers\Admin'],function(){

	Route::get('/', 'UserContoller@login');
	Route::get('login', 'UserContoller@login');
	Route::post('login', [ 'as' => 'login', 'uses' => 'UserContoller@login']);
	Route::post('do-login','UserContoller@do_login');
	Route::get('logout','UserContoller@logout');
	Route::view('forgot_password', 'auth.reset_password')->name('password.reset');
	Route::post('reset-password','UserContoller@reset_password');
    Route::get('save-info','UserContoller@saveinfo');
    Route::get('save-info1','UserContoller@saveinfo1');

	Route::middleware(['admin'])->group(function () {

		Route::get('dashboard','DashboardController@index');
        Route::get('my-profile','DashboardController@myProfile')->name('my.profile');
        Route::get('edit-profile','DashboardController@editProfile')->name('edit.profile');
        Route::post('edit-profile','DashboardController@editProfilePost')->name('edit.profile.post');
		Route::get('change-password','DashboardController@changePassword')->name('change.password');
        Route::post('change-password','DashboardController@changePasswordPost')->name('change.password.post');
		Route::resource('user','UserContoller');
		Route::post('update-status','UserContoller@update_status');
		Route::get('ajax','UserContoller@ajax');
		Route::resource('cms','CmsController');
		Route::resource('content','ContentController');
		Route::resource('category','CategoryController');
		Route::resource('subcategory','SubCategoryController');
		Route::resource('product','ProductController');
		Route::resource('banner','BannerController');
		Route::resource('promocode','PromoCodeController');
		Route::post('banner-add/{id}','PlaylistController@banner_add_post');
		Route::get('profile','UserContoller@profile')->name('profile');
        Route::get('orders/{id?}','OrderController@orders')->name('orders.index');
        Route::resource('order','OrderController');
        Route::get('/update-order-status/{order_id}/{user_id}/{order_Status}','OrderController@update_order_status');
        Route::post('/update-order-status','OrderController@update_order_status1');
        Route::resource('deliverycharge','DeliveryChargeController');
		Route::resource('musiccategory','MusicCategoryController');
		Route::resource('audio','AudioController');
		Route::resource('video','VideoController');
		Route::resource('lyric','LyricController');
		Route::resource('subunit','SubunitController');
		Route::resource('color','ColorController');
		Route::resource('unit','UnitController');



	});


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    public function DeviceToken()
    {
        return $this->hasMany(DeviceToken::class);
    }
    public function OtherAddress()
    {
        return $this->hasMany(OtherAddress::class);
    }
    public function Orders()
    {
        return $this->hasMany(Order::class);
    }
    public function Notifications()
    {
        return $this->hasMany(Notification::class);
    }
    public function getProfilePicAttribute($value) {
        return file_checker($value, 'avatar');
    }

}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')
@section('content')

            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">CMS Pages</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url('dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item" aria-current="page"><a href="{{url('cms')}}">CMS Pages</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Add</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                    
                   <div class="col-md-12">
                       
                    
                    <form class="form-horizontal" enctype="multipart/form-data" action="{{url('cms')}}" method="post" id="exampleValidation">
                    @csrf
                   <div class="card">
                    
                    
                            <div class="card-body">
                            <div class="form-group row">
                                    <label class="col-md-2 m-t-15"></label>
                                    <div class="col-md-10">
                                         <a href="{{url('cms')}}" class="btn btn-info pull-right btn-sm" data-toggle="tooltip" title="All CMS Pages" style="float:right;">
                                            <span class="btn-label">
                                                <i class="fa fa-list"></i>
                                            </span>
                                            All CMS Pages
                                        </a>
                                    </div>
                                </div>
                                
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Title</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="title" name="title" placeholder="Enter Title" value="{{old('title')}}">
                                        <span class="text-danger">{{$errors->first('title')}}</span>
                                    </div>
                                </div>
                               <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Slug</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="slug" name="slug" placeholder="Enter Slug" value="{{old('slug')}}"> 
                                        <span class="text-danger">{{$errors->first('slug')}}</span>

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Content</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" id="editor1" name="content" placeholder="Enter Content" value="{{old('content')}}" >{{old('content')}}</textarea> 
                                        <span class="text-danger">{{$errors->first('content')}}</span>

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Meta Title</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="meta_title" name="meta_title" placeholder="Enter Meta Title" value="{{old('meta_title')}}">

                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Meta Tags</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="meta_tags" name="meta_tags" value="{{old('meta_tags')}}" placeholder="Enter Meta Tags">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-2 m-t-15">Meta Description</label>
                                    <div class="col-md-10">
                                        <textarea class="form-control" id="meta_description" name="meta_description" placeholder="Enter Meta Description" value="{{old('meta_description')}}">{{old('meta_description')}}</textarea>
                                        
                                    </div>
                                </div>
                                
                                
                            </div>
                            <div class="border-top">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                        </div>
                    
                   
                </div>
                <!-- ============================================================== -->
             
                
                <!-- ============================================================== -->
                <!-- Recent comment and chats -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <script src="{{url('assets/libs/jquery/dist/jquery.min.js')}}"></script>
           <script src="//cdn.gaic.com/cdn/ui-bootstrap/0.58.0/js/lib/ckeditor/ckeditor.js"></script>
 
          <script src="//cdn.gaic.com/cdn/ui-bootstrap/0.58.0/js/lib/angular.min.js"></script>
          <script>
        $(document).ready(function(){
              CKEDITOR.editorConfig = function (config) {
            config.language = 'es';
            config.uiColor = '#F7B42C';
            config.height = 300;
            config.toolbarCanCollapse = true;

        };
        CKEDITOR.replace('editor1');
            
            /* validate */

        

        $("#exampleValidation").validate({
            validClass: "success",
            rules: {
                title: {
                    required: true
                },
                slug: {
                    required: true
                },
                content: {
                    required: true
                },
            },
            highlight: function(element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function(element) {
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
            },
        });
         
    
    
        
        
        
        });

        

        
        
        
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('title','Users')
@section('content')
<style>
.cus_box_info
{
    background-color: #24313C; padding: 10px; margin: 10px;
}

.cus_body_box
{
    background-color: #1C2331; padding: 10px; margin: 10px;color:white;
}

.cus_head_box
{
    height: 40px; padding-top:10px; margin-top: 0px; background-color:#1AB188;
}

.detail_cus  { padding-top: 7px; margin-top: 7px; }
.box_footer_cus  { background-color: #1AB188; padding-top: 7px; margin-top: 7px; }


.status_checkbox{
visibility: hidden;
}

/* SLIDE THREE */
.slideparam {
width: 80px;
height: 26px;
background: #333;
margin: 2px auto;

-webkit-border-radius: 50px;
-moz-border-radius: 50px;
border-radius: 50px;
position: relative;

-webkit-box-shadow: inset 0px 1px 1px rgba(0,0,0,0.5), 0px 1px 0px rgba(255,255,255,0.2);
-moz-box-shadow: inset 0px 1px 1px rgba(0,0,0,0.5), 0px 1px 0px rgba(255,255,255,0.2);
box-shadow: inset 0px 1px 1px rgba(0,0,0,0.5), 0px 1px 0px rgba(255,255,255,0.2);

}

.slideparam:after {
content: 'OFF';
font: 12px/26px Arial, sans-serif;
color: #7a121d;
position: absolute;
right: 10px;
z-index: 0;
font-weight: bold;
text-shadow: 1px 1px 0px rgba(255,255,255,.15);
}

.slideparam:before {
content: 'ON';
font: 12px/26px Arial, sans-serif;
color: #00bf00;
position: absolute;
left: 10px;
z-index: 0;
font-weight: bold;
}

.slideparam label {
display: block;
width: 34px;
height: 20px;
cursor: pointer;
-webkit-border-radius: 50px;
-moz-border-radius: 50px;
border-radius: 50px;

-webkit-transition: all .4s ease;
-moz-transition: all .4s ease;
-o-transition: all .4s ease;
-ms-transition: all .4s ease;
transition: all .4s ease;
position: absolute;
top: 3px;
left: 3px;
z-index: 1;

-webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.3);
-moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.3);
box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.3);
background: #fff;


filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcfff4', endColorstr='#b3bead',GradientType=0 );
}

.slideparam input[type=checkbox]:checked + label {
left: 43px;
}


 .slideparam input[type=checkbox]:checked + label:after {
   background: #27ae60;
}

.slideparam label:after {
   content:'';
   width: 10px;
   height: 10px;
   position: absolute;
   top: 5px;
   left: 12px;
   background: red;
   border-radius: 50%;
   box-shadow: inset 0px 1px 1px black, 0px 1px 0px rgba(255, 255, 255, 0.9);
 }

</style>
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Users</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{url(SEGMENT.'/dashboard')}}">Home</a></li>
                                    <li class="breadcrumb-item" aria-current="page"><a href="{{url(SEGMENT.'/user')}}">Users</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">List</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Sales Cards  -->
                <!-- ============================================================== -->
                <div class="row">
                   <div class="col-md-12">
                   @if(session('message'))
                <p class="alert alert-success">{{session('message')}}</p>
            @endif
                   <div class="card">
                            <div class="card-body">

                                 <div class="form-group row">
                                    <label class="col-md-2 m-t-15"> <h5 class="card-title"></h5></label>
                                    <div class="col-md-10">
                                         <!-- <a href="{{url(SEGMENT.'/user/create')}}" class="btn btn-info pull-right btn-sm" data-toggle="tooltip" title="All user Pages" style="float:right;">
                                            <span class="btn-label">
                                                <i class="fa fa-list"></i>
                                            </span>
                                            Add Page
                                        </a> -->
                                    </div>
                                </div>
                                <form action="{{url()->current()}}" >
                                    <div class="form-group row">
                                        <label class="col-md-1 m-t-15"><b>Search</b></label>
                                        <div class="col-md-3">
                                            <input type="text" class="form-control" id="search" name="search" placeholder="Enter Name,Phone no,Email ..." value="{{$search}}" required="">

                                        </div>
                                        <div class="col-md-1">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                        </div>

                                        <div class="col-md-2">
                                        <a href="{{url()->current()}}" class="btn btn-danger">Reset</a>
                                        </div>
                                    </div>
                                </form>

                                <div class="table-responsive m-t-20">
                                    <table id="example1" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Sr</th>
                                                <th>Name</th>
                                                <th>Phone Number</th>
                                                <th>Email</th>
                                                <th>CreatedAt</th>
                                                <th>Profile Pic</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php $i= $users->toArray()['from'] ?? 1; @endphp
                                            @foreach($users as $row)
                                            <tr>
                                                <td>{{$i}}</td>
                                                <td>{{$row->fullname}}</td>
                                                <td>{{ $row->country_code}} {{$row->phone_number}}</td>
                                                <td>{{$row->email}}</td>
                                                <td>{{date('d-M-Y',strtotime($row->created_at))}}</td>
                                                <td><a target="_blank" href="{{$row->profile_pic}}"><img src="{{$row->profile_pic}}" width="50" /></a></td>
                                                <td><center><div class="slideparam">
                    <input type_status="users" type="checkbox" id="{{$row->id}}" onChange="save_admin_message_settings({{$row->id}})" name="status" value="1"  class="status_{{$row->id}} status_checkbox"   {{($row->status==1)?"checked":""}}  />
                    <label for="{{$row->id}}" ></label>
                    </div> </center></td>
                                                <td>

                                    <div class="float-left mr-2">
                                      <!-- <a href="{{ url(SEGMENT.'/user/'.$row->id)}}" class="btn btn-info btn-darken-3 tab-order" > <i class="fa fa-eye"> </i></a> -->
                                    </div>
                                    <div class="float-left">
                                        <form id="delete_entry" action="{{ url(SEGMENT.'/user/'.$row->id) }}" method="POST">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="DELETE">

                                        <button type="button" class="btn btn-danger btn-sm" onclick="delete_entry($(this).parents('form').attr('id'))" data-toggle='tooltip' title="Delete"><i class="fa fa-trash"></i> </button>
                                         </form>

                                    </div>

                                                </td>
                                            </tr>
                                            @php $i++; @endphp
                                            @endforeach

                                    </table>
                                </div>
                                {{ $users->appends(request()->query())}}

                            </div>
                        </div>
                        </div>


                </div>
                <!-- ============================================================== -->


                <!-- ============================================================== -->
                <!-- Recent comment and chats -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->

          @push('scripts')
            <script >
                $(function () {
              $('#example1').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : true,
                'pageLength'  : 50,
                "lengthMenu": [[10, 25, 50], [10, 25, 50]],
                "aoColumns": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                  { "bSortable": false },
                                  { "bSortable": false },
                                  { "bSortable": false }
                              ]

              });


            });
            </script>
         @endpush
@endsection